spring.application.name=order-Service

server.port=8082

spring.datasource.order.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.order.jdbc-url=jdbc:oracle:thin:@//localhost:1521/ORCLPDB
spring.datasource.order.username=ORDER_SERVICE
spring.datasource.order.password=Malinga

spring.datasource.customer.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.customer.jdbc-url=jdbc:oracle:thin:@//localhost:1521/ORCL
spring.datasource.customer.username=MALINGA
spring.datasource.customer.password=malinga

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
